### ISSUE TITLE
errors while doing the fresh install

### ISSUE THREAD

**Issue by aosokin** [timy90022/One-Shot-Object-Detection#11]
Hi, I've just installed your code in a fresh conda env and got the following errors:

- The following packages were required, but are not in requirements.txt: pandas, pillow==6.1.0
- requirements.txt installed scipy 1.4.1, which was crashing on line `from scipy.misc import imread`. Needed to downgrade to 1.1.0
- pycocotools were not compiling with your `lib/setup.py`, had to compile it manually separately

Fixing those might make future installs easier.

**Comment by timy90022** [comment]
Thank you for your update.
