### ISSUE TITLE
Bad results

### ISSUE THREAD

**Issue by trungpham2606** [timy90022/One-Shot-Object-Detection#2]
@timy90022 
I had tried your model in coco valid 2014 set.
and the results are not good.
for example this image:
![image](https://user-images.githubusercontent.com/35657426/70196029-f50bfe00-1739-11ea-9861-7459b014ba74.png)

**Comment by timy90022** [comment]
@trungpham2606 One-shot object detection is currently a very challenging problem and the research is still ongoing. The main challenge is that it is hard to detect the query object that is unseen in training/testing data. Therefore it could be difficult to work well for all unseen query objects. And for this case, it reveals the other challenge that the model should also know the query object is not in the target image. However the current evaluation protocol does not have the standard to evaluate this kind of "false positive". Therefore In our paper, we simplify the problem and assume at least one query object is included in the target image. If the query object does not exist in the target image, our model will detect objects that is the most similar to the query objects. Thanks for playing around our code!

**Comment by trungpham2606** [comment]
@timy90022 Oh i see, thank you for your prompt response!
