### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by pipi2020** [timy90022/One-Shot-Object-Detection#5]
could you please send the demo code so that i can run it to test the trained model with visualization? thank U

**Comment by pipi2020** [comment]
@timy90022

**Comment by howardyclo** [comment]
@pipi2020 Hi, there is a [**Test**](https://github.com/timy90022/One-Shot-Object-Detection#test) section in README that just matches your need. Please AT LEAST read documentation before asking questions that are already in document. Thanks.

**Comment by pipi2020** [comment]
Oh sorry, I'm not very careful？ But I don't know what ‘coco first group ‘ means. Could  you please explain it with an intuitive example?Thank U------------------ 原始邮件 ------------------
发件人: "Yi-Chen (Howard) Lo"<notifications@github.com>
发送时间: 2019年12月21日(星期六) 晚上11:25
收件人: "timy90022/One-Shot-Object-Detection"<One-Shot-Object-Detection@noreply.github.com>;
抄送: "pipi"<787117010@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [timy90022/One-Shot-Object-Detection] demo (#5)



@pipi2020 Hi, there is a Test section in README that just matches your need. Please AT LEAST read documentation before asking questions that are already in document. Thanks.
 
&mdash;

**Comment by howardyclo** [comment]
@pipi2020 The coco groups here are different splits of seen and unseen classes for evaluation as described in the paper.

**Comment by pipi2020** [comment]
Thank you very much for your patience! I apologize for the interruption------------------ 原始邮件 ------------------
发件人: "Yi-Chen (Howard) Lo"<notifications@github.com>
发送时间: 2019年12月21日(星期六) 晚上11:49
收件人: "timy90022/One-Shot-Object-Detection"<One-Shot-Object-Detection@noreply.github.com>;
抄送: "pipi"<787117010@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [timy90022/One-Shot-Object-Detection] demo (#5)



@pipi2020 The coco group here is test splits as described in the paper.
 
&mdash;
